const K = { user: 'unihub_user', subjects: 'unihub_subjects', tasks: 'unihub_tasks', schedule: 'unihub_schedule', notes: 'unihub_notes', goals: 'unihub_goals', attendance: 'unihub_attendance', exams: 'unihub_exams', announcements: 'unihub_announcements', theme: 'unihub_theme', library: 'unihub_library' };
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const get = (k, d = []) => JSON.parse(localStorage.getItem(k) || JSON.stringify(d)); const set = (k, v) => localStorage.setItem(k, JSON.stringify(v));
function seed() { if (!localStorage.getItem(K.subjects)) set(K.subjects, [{ id: 1, name: 'برمجة كائنية التوجه', code: 'CS201', teacher: 'د. أحمد', hours: 3 }, { id: 2, name: 'هياكل البيانات', code: 'CS202', teacher: 'د. محمد', hours: 3 }, { id: 3, name: 'قواعد البيانات', code: 'DB210', teacher: 'د. علي', hours: 3 }, { id: 4, name: 'تصميم الويب', code: 'WEB205', teacher: 'د. خالد', hours: 2 }]); if (!localStorage.getItem(K.tasks)) set(K.tasks, [{ id: 1, title: 'حل واجب OOP', subject: 'برمجة كائنية التوجه', due: '2026-09-25', done: false }, { id: 2, title: 'مراجعة Graph', subject: 'هياكل البيانات', due: '2026-09-27', done: false }, { id: 3, title: 'تصميم صفحة HTML', subject: 'تصميم الويب', due: '2026-09-29', done: true }]); if (!localStorage.getItem(K.goals)) set(K.goals, [{ id: 1, title: 'إنهاء مشروع التخرج', percent: 45 }, { id: 2, title: 'رفع المعدل', percent: 70 }]); if (!localStorage.getItem(K.announcements)) set(K.announcements, [{ title: 'موعد الاختبارات النهائية', text: 'راجع جدول الاختبارات قبل موعدها.' }, { title: 'تسليم المشاريع', text: 'تأكد من رفع ملفات المشروع في الموعد المحدد.' }]); if (!localStorage.getItem(K.exams)) set(K.exams, [{ id: 1, subject: 'برمجة كائنية التوجه', date: '2026-10-10', time: '09:00', room: 'A101' }, { id: 2, subject: 'هياكل البيانات', date: '2026-10-13', time: '11:00', room: 'B202' }]); }
seed();
function user() { return get(K.user, null) } function esc(x) { return String(x ?? '').replace(/[&<>"']/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[m])); }
function nav(active) {
    return `<aside class="sidebar"><div class="side-brand">🎓 UniHub</div><nav class="side">
<a class="${active === 'dashboard' ? 'active' : ''}" href="dashboard.html">🏠 الرئيسية</a><a href="subjects.html">📚 المواد</a><a href="assignments.html">📝 الواجبات</a><a href="schedule.html">📅 الجدول</a><a href="attendance.html">✅ الحضور</a><a href="exams.html">🎓 الاختبارات</a><a href="gpa.html">📊 المعدل</a><a href="notes.html">🗒️ الملاحظات</a><a href="library.html">📁 المكتبة</a><a href="goals.html">🎯 الأهداف</a><a href="announcements.html">📢 الإعلانات</a><a href="pomodoro.html">⏱️ التركيز</a><a href="statistics.html">📈 الإحصائيات</a><a href="calendar.html">🗓️ التقويم</a><a href="profile.html">👤 الملف</a>
</nav></aside>`}
function shell(active, title, body) { if (!user()) { location.href = 'login.html'; return } document.body.classList.toggle('dark', localStorage.getItem(K.theme) === 'dark'); $('#app').innerHTML = `<div class="layout">${nav(active)}<main class="main"><header class="bar"><input class="search" id="globalSearch" placeholder="🔎 بحث في المنصة..." onkeydown="if(event.key==='Enter')doSearch(this.value)"><button class="btn ghost" onclick="toggleTheme()">🌙</button><span class="user-mini">👤 ${esc(user().name)}</span><button class="btn danger" onclick="logout()">خروج</button></header><section class="content"><div class="page-head"><div><h1>${title}</h1><span class="muted">${new Date().toLocaleDateString('ar')}</span></div></div>${body}</section></main></div>` }
function renderApp(page) {
    seed(); const u = user(); if (!u) { if (!location.pathname.endsWith('login.html') && !location.pathname.endsWith('index.html')) location.href = 'login.html'; return } const S = get(K.subjects), T = get(K.tasks), G = get(K.goals);
    if (page === 'dashboard') { let pending = T.filter(x => !x.done).length; let done = T.filter(x => x.done).length; let avg = Math.round(G.reduce((a, x) => a + x.percent, 0) / (G.length || 1)); shell(page, 'لوحة التحكم', `<div class="welcome"><div><h2>أهلاً ${esc(u.name)} 👋</h2><p class="muted">${esc(u.major)} — ${esc(u.id)}</p></div><span class="chip">حساب محلي</span></div><div class="grid"><div class="stat">📚<div class="num">${S.length}</div><span>المواد</span></div><div class="stat">📝<div class="num">${pending}</div><span>واجبات معلقة</span></div><div class="stat">🎯<div class="num">${avg}%</div><span>إنجاز الأهداف</span></div><div class="stat">🏆<div class="num">${done}</div><span>واجبات مكتملة</span></div></div><div class="two"><div class="card"><h3>آخر الواجبات</h3><div class="list">${T.slice(0, 5).map(t => `<div class="item ${t.done ? 'done' : ''}"><span>📝 ${esc(t.title)}<small class="muted"> — ${esc(t.subject)}</small></span><span class="chip">${esc(t.due)}</span></div>`).join('')}</div></div><div class="card"><h3>إعلانات</h3>${get(K.announcements).slice(0, 3).map(a => `<div class="item"><span>📢 ${esc(a.title)}</span></div>`).join('')}</div></div>`) }
    else if (page === 'subjects') subjectPage(); else if (page === 'assignments') taskPage(); else if (page === 'schedule') schedulePage(); else if (page === 'attendance') attendancePage(); else if (page === 'exams') examPage(); else if (page === 'gpa') gpaPage(); else if (page === 'notes') notesPage(); else if (page === 'library') libraryPage(); else if (page === 'goals') goalPage(); else if (page === 'announcements') announcementPage(); else if (page === 'pomodoro') pomoPage(); else if (page === 'statistics') statsPage(); else if (page === 'profile') profilePage(); else if (page === 'calendar') calendarPage();
}
function subjectPage() { shell('subjects', 'المواد الدراسية', `<div class="card"><form class="form-grid" onsubmit="addSubject(event)"><input id="sn" required placeholder="اسم المادة"><input id="sc" placeholder="رمز المادة"><input id="st" placeholder="اسم المدرس"><input id="sh" type="number" value="3" min="1" placeholder="الساعات"><button class="btn primary wide">+ إضافة مادة</button></form></div><br><div class="grid" id="subjectList"></div>`); drawSubjects() }
function drawSubjects() { let S = get(K.subjects); $('#subjectList').innerHTML = S.map(s => `<div class="card"><span class="chip">${esc(s.code)}</span><h3>${esc(s.name)}</h3><p class="muted">👨‍🏫 ${esc(s.teacher)}<br>⏱️ ${s.hours} ساعات</p><button class="btn danger" onclick="delSubject(${s.id})">حذف</button></div>`).join('') || '<div class="empty">لا توجد مواد</div>' }
function addSubject(e) { e.preventDefault(); let S = get(K.subjects); S.push({ id: Date.now(), name: $('#sn').value, code: $('#sc').value, teacher: $('#st').value, hours: +$('#sh').value }); set(K.subjects, S); subjectPage(); toast('تمت إضافة المادة') }
function delSubject(id) { set(K.subjects, get(K.subjects).filter(x => x.id !== id)); subjectPage() }
function taskPage() { shell('assignments', 'إدارة الواجبات', `<div class="card"><form class="form-grid" onsubmit="addTask(event)"><input id="tn" required placeholder="عنوان الواجب"><input id="ts" placeholder="المادة"><input id="td" type="date" required><button class="btn primary">+ إضافة</button></form></div><br><div class="card"><input class="search" id="taskSearch" oninput="drawTasks(this.value)" placeholder="🔎 ابحث عن واجب..."></div><br><div class="list" id="taskList"></div>`); drawTasks('') }
function drawTasks(q = '') { let T = get(K.tasks).filter(t => (t.title + t.subject).toLowerCase().includes(q.toLowerCase())); $('#taskList').innerHTML = T.map(t => `<div class="item ${t.done ? 'done' : ''}"><div><b>${esc(t.title)}</b><div class="muted">${esc(t.subject)} — موعد: ${esc(t.due)}</div></div><div class="actions-sm"><button class="btn success" onclick="toggleTask(${t.id})">${t.done ? 'إرجاع' : 'تم'}</button><button class="btn danger" onclick="delTask(${t.id})">حذف</button></div></div>`).join('') || '<div class="empty">لا توجد واجبات</div>' }
function addTask(e) { e.preventDefault(); let T = get(K.tasks); T.push({ id: Date.now(), title: $('#tn').value, subject: $('#ts').value, due: $('#td').value, done: false }); set(K.tasks, T); taskPage() }
function toggleTask(id) { let T = get(K.tasks); T = T.map(t => t.id === id ? { ...t, done: !t.done } : t); set(K.tasks, T); taskPage() } function delTask(id) { set(K.tasks, get(K.tasks).filter(x => x.id !== id)); taskPage() }
function schedulePage() { shell('schedule', 'الجدول الأسبوعي', `<div class="card"><form class="form-grid" onsubmit="addSchedule(event)"><input id="day" required placeholder="اليوم: الأحد"><input id="time" required placeholder="الوقت: 08:00"><input id="course" required placeholder="المادة"><input id="room" placeholder="القاعة"><button class="btn primary wide">+ إضافة للحصة</button></form></div><br><div class="list" id="scheduleList"></div>`); drawSchedule() }
function drawSchedule() { let A = get(K.schedule); $('#scheduleList').innerHTML = A.map(x => `<div class="item"><b>📅 ${esc(x.day)} — ${esc(x.time)}</b><span>${esc(x.course)} ${x.room ? `(${esc(x.room)})` : ''}</span><button class="btn danger" onclick="delSchedule(${x.id})">حذف</button></div>`).join('') || '<div class="empty">لم تضف جدولاً بعد</div>' }
function addSchedule(e) { e.preventDefault(); let A = get(K.schedule); A.push({ id: Date.now(), day: $('#day').value, time: $('#time').value, course: $('#course').value, room: $('#room').value }); set(K.schedule, A); schedulePage() } function delSchedule(id) { set(K.schedule, get(K.schedule).filter(x => x.id !== id)); schedulePage() }
function attendancePage() { let S = get(K.subjects); shell('attendance', 'سجل الحضور', `<div class="card"><p class="muted">سجل محلي لحضور كل مادة. النسبة تحسب تلقائياً.</p><div class="table-wrap"><table class="table"><tr><th>المادة</th><th>المحاضرات</th><th>الحضور</th><th>النسبة</th><th>إجراء</th></tr>${S.map(s => { let a = get(K.attendance).find(x => x.sid === s.id) || { total: 0, present: 0 }; let p = a.total ? Math.round(a.present / a.total * 100) : 0; return `<tr><td>${esc(s.name)}</td><td>${a.total}</td><td>${a.present}</td><td><span class="chip">${p}%</span></td><td><button class="btn primary" onclick="att(${s.id},1)">حضر</button> <button class="btn ghost" onclick="att(${s.id},0)">غاب</button></td></tr>` }).join('')}</table></div></div>`) }
function att(sid, present) { let A = get(K.attendance), x = A.find(a => a.sid === sid); if (!x) { x = { sid, total: 0, present: 0 }; A.push(x) } x.total++; if (present) x.present++; set(K.attendance, A); attendancePage() }
function examPage() { let E = get(K.exams); shell('exams', 'جدول الاختبارات', `<div class="card"><form class="form-grid" onsubmit="addExam(event)"><input id="es" required placeholder="المادة"><input id="ed" type="date" required><input id="et" placeholder="الوقت"><input id="er" placeholder="القاعة"><button class="btn primary wide">+ إضافة اختبار</button></form></div><br><div class="list">${E.map(e => `<div class="item"><div>🎓 <b>${esc(e.subject)}</b><div class="muted">${esc(e.date)} — ${esc(e.time)} — قاعة ${esc(e.room)}</div></div><button class="btn danger" onclick="delExam(${e.id})">حذف</button></div>`).join('')}</div>`) }
function addExam(e) { e.preventDefault(); let E = get(K.exams); E.push({ id: Date.now(), subject: $('#es').value, date: $('#ed').value, time: $('#et').value, room: $('#er').value }); set(K.exams, E); examPage() } function delExam(id) { set(K.exams, get(K.exams).filter(x => x.id !== id)); examPage() }
function gpaPage() { shell('gpa', 'حساب المعدل GPA', `<div class="card"><p class="muted">أدخل الساعات والتقدير لكل مقرر. التقديرات: A=4, B=3, C=2, D=1, F=0.</p><div id="gpaRows"></div><button class="btn ghost" onclick="addGpaRow()">+ مقرر</button> <button class="btn primary" onclick="calcGpa()">احسب المعدل</button><h2 id="gpaResult"></h2></div>`); addGpaRow(); addGpaRow(); addGpaRow() }
function addGpaRow() { let d = document.createElement('div'); d.className = 'form-grid'; d.innerHTML = '<input class="gname" placeholder="اسم المادة"><input class="gh" type="number" min="1" value="3" placeholder="الساعات"><select class="gg"><option>A</option><option>B</option><option>C</option><option>D</option><option>F</option></select>'; $('#gpaRows').appendChild(d) }
function calcGpa() { let map = { A: 4, B: 3, C: 2, D: 1, F: 0 }, h = 0, p = 0; $$('#gpaRows .form-grid').forEach(r => { let hr = +r.querySelector('.gh').value, g = map[r.querySelector('.gg').value]; h += hr; p += hr * g }); $('#gpaResult').textContent = h ? 'المعدل: ' + (p / h).toFixed(2) + ' / 4.00' : 'أدخل البيانات' }
function notesPage() { shell('notes', 'الملاحظات', `<div class="card"><form class="form-grid" onsubmit="addNote(event)"><input id="nt" required placeholder="عنوان الملاحظة"><textarea id="nb" class="wide" rows="4" required placeholder="اكتب ملاحظتك..."></textarea><button class="btn primary wide">حفظ الملاحظة</button></form></div><br><div class="three" id="notesList"></div>`); drawNotes() }
function drawNotes() { let N = get(K.notes); $('#notesList').innerHTML = N.map(n => `<div class="card"><h3>${esc(n.title)}</h3><p class="note">${esc(n.body)}</p><button class="btn danger" onclick="delNote(${n.id})">حذف</button></div>`).join('') || '<div class="empty">لا توجد ملاحظات</div>' }
function addNote(e) { e.preventDefault(); let N = get(K.notes); N.unshift({ id: Date.now(), title: $('#nt').value, body: $('#nb').value }); set(K.notes, N); notesPage() } function delNote(id) { set(K.notes, get(K.notes).filter(x => x.id !== id)); notesPage() }
function libraryPage() { shell('library', 'المكتبة الدراسية', `<div class="card"><p>يمكنك اختيار ملفات من جهازك لفتحها أو تنزيلها. بسبب حماية المتصفح، الملفات المختارة لا تصبح قاعدة ملفات سحابية مشتركة.</p><input type="file" id="fileInput" multiple accept=".pdf,.doc,.docx,.ppt,.pptx,.txt,.jpg,.png"><div id="fileList" class="list" style="margin-top:15px"></div></div>`); $('#fileInput').onchange = e => { let A = [...e.target.files]; $('#fileList').innerHTML = A.map(f => `<div class="item">📄 <b>${esc(f.name)}</b><span class="muted">${Math.round(f.size / 1024)} KB</span></div>`).join('') } }
function goalPage() { shell('goals', 'الأهداف الدراسية', `<div class="card"><form class="form-grid" onsubmit="addGoal(event)"><input id="gn" required placeholder="اسم الهدف"><input id="gp" type="number" min="0" max="100" value="0" placeholder="نسبة الإنجاز"><button class="btn primary wide">+ إضافة هدف</button></form></div><br><div class="list">${get(K.goals).map(g => `<div class="item"><div style="flex:1"><b>${esc(g.title)}</b><div class="progress"><i style="width:${g.percent}%"></i></div></div><span>${g.percent}%</span><button class="btn danger" onclick="delGoal(${g.id})">حذف</button></div>`).join('')}</div>`) }
function addGoal(e) { e.preventDefault(); let G = get(K.goals); G.push({ id: Date.now(), title: $('#gn').value, percent: +$('#gp').value }); set(K.goals, G); goalPage() } function delGoal(id) { set(K.goals, get(K.goals).filter(x => x.id !== id)); goalPage() }
function announcementPage() { shell('announcements', 'الإعلانات والتنبيهات', `<div class="list">${get(K.announcements).map(a => `<div class="item"><div>📢 <b>${esc(a.title)}</b><p class="muted">${esc(a.text)}</p></div></div>`).join('')}</div>`) }
let timer = null, seconds = 1500, sessions = 0; function pomoPage() { shell('pomodoro', 'مؤقت التركيز Pomodoro', `<div class="card timer"><div class="clock" id="clock">25:00</div><p class="muted">25 دقيقة تركيز ثم 5 دقائق راحة.</p><button class="btn primary" onclick="startPomo()">بدء</button> <button class="btn ghost" onclick="pausePomo()">إيقاف</button> <button class="btn ghost" onclick="resetPomo()">إعادة</button><h3>جلسات مكتملة: <span id="sessions">${sessions}</span></h3></div>`) }
function paintTimer() { let m = String(Math.floor(seconds / 60)).padStart(2, '0'), s = String(seconds % 60).padStart(2, '0'); let c = $('#clock'); if (c) c.textContent = m + ':' + s } function startPomo() { clearInterval(timer); timer = setInterval(() => { if (seconds > 0) { seconds--; paintTimer() } else { sessions++; clearInterval(timer); toast('انتهت الجلسة! خذ استراحة.') } }, 1000) } function pausePomo() { clearInterval(timer) } function resetPomo() { clearInterval(timer); seconds = 1500; paintTimer() }
function statsPage() { let T = get(K.tasks), S = get(K.subjects), G = get(K.goals), A = get(K.attendance); let done = T.filter(x => x.done).length, rate = T.length ? Math.round(done / T.length * 100) : 0; let ar = [{ n: 'الواجبات', v: rate }, { n: 'الأهداف', v: Math.round(G.reduce((a, x) => a + x.percent, 0) / (G.length || 1)) }, { n: 'الحضور', v: A.length ? Math.round(A.reduce((a, x) => a + (x.total ? x.present / x.total * 100 : 0), 0) / A.length) : 0 }]; shell('statistics', 'الإحصائيات', `<div class="grid"><div class="stat">📚<div class="num">${S.length}</div>مواد</div><div class="stat">📝<div class="num">${T.length}</div>واجبات</div><div class="stat">🎯<div class="num">${G.length}</div>أهداف</div><div class="stat">📈<div class="num">${rate}%</div>إنجاز الواجبات</div></div><br><div class="card"><h3>مؤشرات الأداء</h3><div class="chart">${ar.map(x => `<div class="barx" style="height:${Math.max(15, x.v)}%"><span>${x.v}%</span><small>${x.n}</small></div>`).join('')}</div></div>`) }
function profilePage() { let u = user(); shell('profile', 'الملف الشخصي', `<div class="card"><form class="form-grid" onsubmit="saveProfile(event)"><label>الاسم<input id="pn" value="${esc(u.name)}"></label><label>الرقم الجامعي<input id="pi" value="${esc(u.id)}"></label><label>التخصص<input id="pm" value="${esc(u.major)}"></label><label>البريد<input id="pe" value="${esc(u.email || '')}"></label><button class="btn primary wide">حفظ الملف</button></form><br><button class="btn danger" onclick="clearAll()">مسح بيانات المشروع بالكامل</button></div>`) }
function saveProfile(e) { e.preventDefault(); set(K.user, { name: $('#pn').value, id: $('#pi').value, major: $('#pm').value, email: $('#pe').value }); profilePage(); toast('تم حفظ الملف') }
function clearAll() { if (confirm('سيتم حذف كل بيانات UniHub من هذا المتصفح. هل أنت متأكد؟')) { Object.values(K).forEach(k => localStorage.removeItem(k)); location.href = 'index.html' } }
function calendarPage() { let now = new Date(), y = now.getFullYear(), m = now.getMonth(), days = new Date(y, m + 1, 0).getDate(), html = ''; for (let i = 1; i <= days; i++) { let d = new Date(y, m, i); let ev = get(K.exams).filter(e => e.date === `${y}-${String(m + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}`); html += `<div class="day"><b>${i}</b>${ev.map(e => `<span class="chip">🎓 ${esc(e.subject)}</span>`).join('')}</div>` } shell('calendar', 'التقويم الشهري', `<div class="card"><h3>${now.toLocaleDateString('ar', { month: 'long', year: 'numeric' })}</h3><div class="calendar">${html}</div></div>`) }
function doSearch(q) { q = q.trim(); if (!q) return; let T = get(K.tasks).filter(x => (x.title + x.subject).includes(q)), S = get(K.subjects).filter(x => (x.name + x.code + x.teacher).includes(q)); alert(`نتائج البحث: ${T.length} واجب، ${S.length} مادة. افتح الواجبات أو المواد لرؤية التفاصيل.`) }
function toggleTheme() { let d = localStorage.getItem(K.theme) === 'dark'; localStorage.setItem(K.theme, d ? 'light' : 'dark'); document.body.classList.toggle('dark', !d) }
function logout() { localStorage.removeItem(K.user); location.href = 'login.html' } function toast(s) { let d = document.createElement('div'); d.className = 'toast'; d.textContent = s; document.body.appendChild(d); setTimeout(() => d.remove(), 2200) }
document.addEventListener('DOMContentLoaded', () => { let f = $('#loginForm'); if (f) f.onsubmit = e => { e.preventDefault(); set(K.user, { name: $('#loginName').value, id: $('#loginId').value, major: $('#loginMajor').value, email: '' }); location.href = 'dashboard.html' } });
